"""Reproducible DTO generation; schema is the source of truth. No network."""
import json, pathlib, sys
ROOT = pathlib.Path(__file__).resolve().parents[1]
schema = json.loads((ROOT/'packages/contracts/chat.schema.json').read_text())
defs = schema['$defs']
defs.update(json.loads((ROOT/'packages/contracts/resources.schema.json').read_text())['$defs'])
cs = ['// Generated by tools/build-contracts.py. Do not edit.', 'namespace Companion.Contracts {']
ts = ['// Generated by tools/build-contracts.py. Do not edit.']
def ctype(p):
    if '$ref' in p: return p['$ref'].split('/')[-1]
    if 'anyOf' in p:
        t=ctype(p['anyOf'][0]); return t+'?' if t in ('int','bool','double') else t
    if p.get('type')=='array': return ctype(p['items'])+'[]'
    if p.get('type')=='object' and isinstance(p.get('additionalProperties'),dict): return 'System.Collections.Generic.Dictionary<string, '+ctype(p['additionalProperties'])+'>'
    if isinstance(p.get('const'), int): return 'int'
    return {'integer':'int','number':'double','boolean':'bool','string':'string','object':'object'}.get(p.get('type'),'string')
def ttype(p):
    if '$ref' in p: return p['$ref'].split('/')[-1]
    if 'anyOf' in p: return ttype(p['anyOf'][0])+' | null'
    if p.get('type')=='array': return '('+ttype(p['items'])+')[]'
    if p.get('type')=='object' and isinstance(p.get('additionalProperties'),dict): return 'Record<string, '+ttype(p['additionalProperties'])+'>'
    if 'properties' in p: return '{ '+ '; '.join(k+('' if k in p.get('required',[]) else '?')+': '+ttype(v) for k,v in p['properties'].items())+' }'
    if 'const' in p: return json.dumps(p['const'])
    if 'enum' in p: return ' | '.join(json.dumps(v) for v in p['enum'])
    return {'integer':'number','number':'number','boolean':'boolean','string':'string','object':'Record<string, unknown>'}.get(p.get('type'),'unknown')
for name, definition in defs.items():
    if 'properties' not in definition: continue
    cs += ['[System.Serializable] public sealed class '+name+' {']
    ts += ['export interface '+name+' {']
    for field, prop in definition['properties'].items():
        typ=ctype(prop)
        if field not in definition.get('required',[]) and typ in ('int','double','bool'): typ+='?'
        cs += ['    public '+typ+' '+field+';']
        ts += ['  '+field+('' if field in definition.get('required',[]) else '?')+': '+ttype(prop)+';']
    cs += ['}']; ts += ['}']
cs += ['}']
# Typed transport facade generated from the implemented OpenAPI operations. Transport
# implementations own serialization, auth and SSE; no vendor SDK enters Core.
api=json.loads((ROOT/'packages/contracts/openapi.json').read_text())
client=['// Generated by tools/build-contracts.py. Do not edit.','using System; using System.Threading; using System.Threading.Tasks;','namespace Companion.Contracts {',
 'public interface IContractTransport { Task<TResponse> Request<TRequest,TResponse>(string method,string path,TRequest body,string idempotencyKey,CancellationToken cancel); }',
 'public sealed class CompanionClient { readonly IContractTransport transport; public CompanionClient(IContractTransport transport) { this.transport=transport; }']
tsclient=['// Generated by tools/build-contracts.py. Do not edit.','import type * as Models from "./contracts.ts";',
 'export interface ContractTransport { request<T>(method:string,path:string,body:unknown,key:string|null,signal?:AbortSignal):Promise<T>; }',
 'export class CompanionClient { private transport: ContractTransport; constructor(transport: ContractTransport) { this.transport=transport; }']
for path,methods in api['paths'].items():
    for method,op in methods.items():
        name=op['operationId'][0].upper()+op['operationId'][1:]
        response=next(iter(op['responses'].values()))['content'];mime=next(iter(response));ret='string' if mime=='text/event-stream' else response[mime]['schema']['$ref'].split('/')[-1]
        request=op.get('requestBody',{}).get('content',{}).get('application/json',{}).get('schema',{}).get('$ref','').split('/')[-1]
        csargs='Guid id, '+(('SendMessage body, string key, ') if request else '')+'CancellationToken cancel'
        route='"'+path.replace('{id}','" + id.ToString() + "')+'"'
        client+=['public Task<'+ret+'> '+name+'('+csargs+') { return transport.Request<'+(request or 'object')+','+ret+'>("'+method.upper()+'",'+route+','+('body,key' if request else 'null,null')+',cancel); }']
        tsret='string' if ret=='string' else 'Models.'+ret
        tsclient+=['  '+name+'(id:string, '+('body:Models.SendMessage,key:string,' if request else '')+'signal?:AbortSignal):Promise<'+tsret+'> { return this.transport.request<'+tsret+'>("'+method.upper()+'",`'+path.replace('{id}','${encodeURIComponent(id)}')+'`,'+('body,key' if request else 'null,null')+',signal); }']
client+=['}}'];tsclient+=['}']
outputs = {
 'packages/contracts/generated/Contracts.cs':'\n'.join(cs)+'\n',
 'apps/unity/Assets/Companion/Core/Generated/Contracts.cs':'\n'.join(cs)+'\n',
 'packages/contracts/generated/contracts.ts':'\n'.join(ts)+'\n',
 'packages/contracts/generated/CompanionClient.cs':'\n'.join(client)+'\n',
 'apps/unity/Assets/Companion/Core/Generated/CompanionClient.cs':'\n'.join(client)+'\n',
 'packages/contracts/generated/client.ts':'\n'.join(tsclient)+'\n'
}
for path, text in outputs.items():
    p=ROOT/path
    if '--check' in sys.argv:
        if not p.exists() or p.read_text()!=text: raise SystemExit('Generated drift: '+path)
    else: p.parent.mkdir(parents=True,exist_ok=True); p.write_text(text,encoding='utf-8')
print('PASS generated C#/TypeScript contract drift' if '--check' in sys.argv else 'Generated C#/TypeScript DTOs')
